from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any

from pydantic import BaseModel, Field, HttpUrl

# --- Enums ---
class ArtifactType(str, Enum):
    """The type of the artifact being registered."""
    model = "model"
    dataset = "dataset"
    code = "code"

# --- Metrics and Rating Schemas (Derived from OpenAPI snippet) ---
class Metric(BaseModel):
    """A single metric result, part of a ModelRating."""
    name: str = Field(..., description="Name of the computed metric (e.g., net_score, recall).")
    value: float = Field(..., description="Numeric value of the metric.")
    unit: str = Field(..., description="Unit associated with the metric value (e.g., 'ratio', 's', 'USD').")

class ModelRating(BaseModel):
    """Collection of metrics that define the artifact's trustworthiness score."""
    metrics: List[Metric] = Field(..., description="List of computed trustworthiness metrics.")
    # Add other high-level rating info if needed later

# --- Request/Input Schemas ---
class ArtifactData(BaseModel):
    """The input structure for a user requesting artifact ingestion."""
    url: HttpUrl = Field(..., description="The original public URL to the model/dataset/code artifact.")
    artifact_type: ArtifactType = Field(..., description="The type of artifact being ingested.")
    name: Optional[str] = Field(None, description="Optional human-readable name for the artifact (derived if missing).")

# --- Response/Output Schemas ---
class Artifact(BaseModel):
    """The complete representation of an artifact stored in the registry."""
    artifact_id: str = Field(..., description="Unique immutable identifier generated by the registry.")
    artifact_type: ArtifactType = Field(..., description="The type of the artifact.")
    name: str = Field(..., description="Human-readable name of the artifact.")
    original_url: str = Field(..., description="The original URL provided by the user.")
    s3_key: str = Field(..., description="Internal S3 path to the binary artifact file.")
    ingest_date: datetime = Field(..., description="Timestamp when the artifact was successfully ingested.")
    rating_data: ModelRating = Field(..., description="The trustworthiness evaluation scores.")
    lineage_graph: Dict[str, Any] = Field(..., description="Placeholder for the dependency graph data.")
    cost_data: Dict[str, Any] = Field(..., description="Placeholder for computed cost information.")
